name: Ubuntu 20.04 ROS Noetic

on:
  push:
    branches: [ ros2-support ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docker:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:focal
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic
        
