name: Ubuntu 24.04 ROS Jazzy

on:
  push:
    branches: [ ros2-support ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docker:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:noble

    steps:
      - name: Install ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Install missing debian packages
        shell: bash
        run: |
          sudo apt-get install --yes ros-jazzy-rosidl-cmake python3-vcstool python3-colcon-common-extensions libasound2-dev libgl1-mesa-dev xorg-dev libusb-1.0-0-dev libboost-filesystem-dev 

      - name: Create Workspace
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          mkdir -p ~/ros2_ws/src

      - name: Retrieve Code
        shell: bash
        run: |
          cd ~/ros2_ws/src
          vcs import --input https://raw.githubusercontent.com/LauraConnolly/ambf/ros2-support/ambf.repos

      - name: Compile
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          cd ~/ros2_ws
          colcon build
