name: Ubuntu 20.04 ROS Galactic

on:
  push:
    branches: [ ros2-support ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
      - name: Compile AMBF
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: galactic
          vcs-repo-file-url: https://raw.githubusercontent.com/LauraConnolly/ambf/ros2-support/ambf.repos
