name: Ubuntu 20.04 ROS Noetic

on:
  push:
    branches: [ ros2-support ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docker:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:focal

    steps:
      - name: Install ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic

      - name: Create Workspace
        run: |
          source /opt/ros/noetic/setup.bash
          mkdir -p ~/catkin_ws/src
          cd ~/catkin_ws
          catkin init
          catkin build
          
      - name: Retrieve Code
        run: |
          cd ~/catkin_ws/src
          vcs import --input https://raw.githubusercontent.com/LauraConnolly/ambf/ros2-support/ambf.repos

      - name: Compile
        run: |
          source ~/catkin_ws/devel/setup.bash
          cd ~/catkin_ws
          catkin build --no-status --summary     
